### ISSUE TITLE
Still awaiting Obsidian proper LP rendering

### ISSUE THREAD

**Issue by DutchPete** [ganesshkumar/obsidian-excel-to-markdown-table#1]
This is a great plug-in and am very eager to use it, but ……… Obsidian does not render tables in Live Preview as in Reading mode à la Typora. I am using Typora only for notes with tables because the rendering is fantastic.

Unfortunately, as WhiteNoise [stated](https://forum.obsidian.md/t/live-preview-add-support-for-tables-render-tables-as-per-reading-view/29100/13?u=klaas) 4 weeks ago, it won't happen in the short term.

**Comment by ganesshkumar** [comment]
Thanks @DutchPete . The plugin is live in the community plugins list. Try it and let me know if there is any feedback.

Closing this issue

**Comment by DutchPete** [comment]
Thank you. Yes, it works, but like I stated above, Live Preview does not yet render tables as in Reading mode. Since I mostly use LP mode, there is no point in my using this otherwise excellent plug-in yet. 😭
