### ISSUE TITLE
[BUG] Pipe characters in excel cells are not escaped when pasted into Obsidian.

### ISSUE THREAD

**Issue by reticulator** [ganesshkumar/obsidian-excel-to-markdown-table#11]
**Describe the bug**
Pipe `|` characters in excel cells are not escaped when pasted into Obsidian.

**To Reproduce**
1. Create table in excel and enter a pipe `|` character somewhere inside the cell
![image](https://user-images.githubusercontent.com/18054967/173196102-c02b4466-1378-41ed-9d83-8f2654e54c59.png)
2. Copy and paste the table into Obsidian
3. Source code looks like
```
| Column 1        | Column2 |
|-----------------|---------|
| Value1a|Value1b | Value2  |
```

**Expected behavior**
The pipe character should be escaped.
```
| Column 1         | Column2 |
|------------------|---------|
| Value1a\|Value1b | Value2  |
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
According to https://www.markdownguide.org/extended-syntax/#escaping-pipe-characters-in-tables

>  You can display a pipe (|) character in a table by using its HTML character code (\&#124;).

But it also doesn't specifically say you should not use the `\` escape character which is a valid [escape code](https://www.markdownguide.org/basic-syntax/#characters-you-can-escape) and using `\|` does seem to render the table correctly which would be my preferred method as it's easier to remember.  Perhaps this should be a configurable user option in case other users have a different preference.

**Comment by ganesshkumar** [comment]
@reticulator Please verify the fix in the latest version

**Comment by reticulator** [comment]
I upgraded to `0.4.0` and pasting in data with a pipe character is now correctly escaped, though I noticed the header padding is short by one character.  I guess this would only be a problem if your value with the escaped pipe is the longest value.  

This is what I see now
```
| Column 1        | Column2 |
|-----------------|---------|
| Value1a\|Value1b | Value2  |
```

and this is what I would expect
```
| Column 1         | Column2 |
|------------------|---------|
| Value1a\|Value1b | Value2  |
```
