### ISSUE TITLE
[BUG] Prompt: Fail to load, on IOS

### ISSUE THREAD

**Issue by aooaa** [ganesshkumar/obsidian-excel-to-markdown-table#18]
**Describe the bug**
Plugin Can't load properly on IOS, and prompt: Fail to load xxx, when start Obsidian.

**To Reproduce**
1. install plugin on IOS
2. enable plugin 
3. See error: Fail to load xxx

**Expected behavior**
Load successfully without warning. 

**Screenshots**
![image](https://user-images.githubusercontent.com/37745896/196928153-4c9cc24e-c4d1-46a6-9901-71c5f6905c1a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version v1.0.0

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS16.0.2
 - Version v1.4.0

**Comment by marcusmoore** [comment]
I think this is the issue as seen in #10

**Comment by aooaa** [comment]
Yes, same issue, I will check, thanks.👌

**Comment by aooaa** [comment]
Still unsolved, 🙃

**Comment by marcusmoore** [comment]
Yeah, there is an open issue on the upstream package: https://github.com/csholmq/vscode-excel-to-markdown-table/issues/28

The other day I noticed that the Safari section of the Settings app in iOS has an Experimental Features page. I didn't scroll through but I wondered if there is a flag that can be turned on in there to enable the use of lookbehind regexes.

**Comment by aooaa** [comment]
It seems the problem of Safari,Lookbehind in JS regular expressions is not supported on Safari 7.1 by far.
